### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by jdegoes** [purescript/purescript-invariant#2]
I was going to create this. :)

Can I suggest changing the name of the class to `IFunctor`, and the name of the map function to `imap`? The other name people use for this is `XFunctor`, `xmap`, etc., but personally I prefer `IFunctor` / `imap`.

**Comment by garyb** [comment]
Good call on the `imap` yep, and I should probably have mentioned something along the lines of "also known as an exponential functor" in the docs.

As for `IFunctor`, I can see why, as `Invariant` is a bit vague perhaps, but should we be reconsidering the name of `Contravariant` as well then?

**Comment by jdegoes** [comment]
I'd prefer `Contravariant` be `ContraFunctor` or some such. There are an infinitely many things which are invariant and contravariant, and no particular reason why covariant functors should be the only ones to get `Functor` in the name somewhere.

Just my 2 cents, of course.

**Comment by LiamGoodacre** [comment]
Closing as this looks like a stale issue.  I don't see much point in renaming now, `Data.Functor.Invariant` seems appropriate enough.  Please reopen otherwise.
