### ISSUE TITLE
Consider adding `control` dependency and `Alternate` instance

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-invariant#9]
See discussion in https://github.com/purescript/purescript-prelude/issues/179

**Comment by JordanMartinez** [comment]
To clarify, is this just adding [Alternate](https://pursuit.purescript.org/packages/purescript-monoid/3.3.0/docs/Data.Monoid.Alternate) as a newtype here and adding an `Invariant` instance for it?

**Comment by hdgarrood** [comment]
Not quite - Alternate now lives in `control`, see https://github.com/purescript/purescript-control/pull/50. The idea is to add a `control` dependency on this library so that we can add an Invariant Alternate instance here.
